version: '2'
services:
  web:
    build: .
    ports:
      - "5500:5500"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
