version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/auth-server
      - PORT=80   
      - DEBUG=*
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
      - ./docker/data:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth-server